# Generated by Django 2.2 on 2020-09-09 18:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import dp27app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[dp27app.models.validatename])),
                ('url', models.URLField(max_length=100, unique=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp27app.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='AccessDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp27app.WebPage')),
            ],
        ),
    ]
